# Site wide configuration

title: Sirwisa Brewing Collective
locale: en_US
description: We work together to further the love of brewing and support the community we live in.
logo: site-logo.png
search: false
url: 


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Sirwisa Brewing Collective
  avatar: bio-photo.jpg
  email: info@sirwisabrewingcollective.com
  disqus-shortname:
  twitter: SirwisaBrewing
  facebook: sirwisabrewingcollective
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: sirwisabrewingcollective
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify: